/**
 * Resume Feedback Service
 * Handles all database operations for resume comments, checklists, and evaluations
 */

import { db } from "@/integrations/drizzle/client";
import {
	resumeComment,
	resumeChecklist,
	resumeChecklistItem,
	resumeEvaluation,
	resumeEvaluationItem,
	resumeHistory,
} from "@/integrations/drizzle/schema";
import { eq, and, desc } from "drizzle-orm";

/**
 * CREATE: Add a comment to a resume
 */
export async function createComment({
	resumeId,
	studentId,
	tenantId,
	authorId,
	content,
	scope = "INDIVIDUAL",
}: {
	resumeId: string;
	studentId: string;
	tenantId: string;
	authorId: string;
	content: string;
	scope?: "INDIVIDUAL" | "SECTION";
}) {
	const result = await db
		.insert(resumeComment)
		.values({
			id: crypto.randomUUID(),
			resumeId,
			studentId,
			tenantId,
			authorId,
			content,
			scope,
			status: "PUBLISHED",
			createdAt: new Date(),
			updatedAt: new Date(),
		})
		.returning();

	return result[0];
}

/**
 * READ: List comments for a resume
 */
export async function getCommentsByResumeId(resumeId: string) {
	const comments = await db
		.select()
		.from(resumeComment)
		.where(eq(resumeComment.resumeId, resumeId))
		.orderBy(desc(resumeComment.createdAt));

	return comments;
}

/**
 * UPDATE: Update a comment (status, content)
 */
export async function updateComment(
	commentId: string,
	updates: {
		content?: string;
		status?: "DRAFT" | "PUBLISHED" | "RESOLVED";
		resolvedAt?: Date | null;
	}
) {
	const result = await db
		.update(resumeComment)
		.set({
			...updates,
			updatedAt: new Date(),
		})
		.where(eq(resumeComment.id, commentId))
		.returning();

	return result[0];
}

/**
 * DELETE: Soft delete a comment (set status to RESOLVED or add resolvedAt)
 */
export async function softDeleteComment(commentId: string) {
	const result = await db
		.update(resumeComment)
		.set({
			status: "RESOLVED",
			resolvedAt: new Date(),
			updatedAt: new Date(),
		})
		.where(eq(resumeComment.id, commentId))
		.returning();

	return result[0];
}

/**
 * CREATE: Create an evaluation checklist
 */
export async function createChecklist({
	facultyId,
	tenantId,
	courseId,
	title,
	description,
	items,
}: {
	facultyId: string;
	tenantId: string;
	courseId?: string;
	title: string;
	description?: string;
	items: Array<{
		title: string;
		description?: string;
		weight?: number;
		order?: number;
	}>;
}) {
	const checklistId = crypto.randomUUID();

	// Create checklist
	const checklistResult = await db
		.insert(resumeChecklist)
		.values({
			id: checklistId,
			facultyId,
			tenantId,
			courseId,
			title,
			description,
			isActive: true,
			createdAt: new Date(),
			updatedAt: new Date(),
		})
		.returning();

	// Create items
	const itemsResult = await db
		.insert(resumeChecklistItem)
		.values(
			items.map((item, index) => ({
				id: crypto.randomUUID(),
				checklistId,
				title: item.title,
				description: item.description,
				weight: item.weight ?? 1.0,
				order: item.order ?? index,
				createdAt: new Date(),
				updatedAt: new Date(),
			}))
		)
		.returning();

	return {
		...checklistResult[0],
		items: itemsResult,
	};
}

/**
 * READ: Get checklist by ID with items
 */
export async function getChecklistById(checklistId: string) {
	const checklist = await db
		.select()
		.from(resumeChecklist)
		.where(eq(resumeChecklist.id, checklistId));

	if (!checklist.length) return null;

	const items = await db
		.select()
		.from(resumeChecklistItem)
		.where(eq(resumeChecklistItem.checklistId, checklistId))
		.orderBy(resumeChecklistItem.order);

	return {
		...checklist[0],
		items,
	};
}

/**
 * READ: List checklists by faculty or course
 */
export async function listChecklists({
	facultyId,
	courseId,
	tenantId,
}: {
	facultyId?: string;
	courseId?: string;
	tenantId: string;
}) {
	const conditions = [eq(resumeChecklist.tenantId, tenantId)];

	if (facultyId) {
		conditions.push(eq(resumeChecklist.facultyId, facultyId));
	}

	if (courseId) {
		conditions.push(eq(resumeChecklist.courseId, courseId));
	}

	return await db
		.select()
		.from(resumeChecklist)
		.where(and(...conditions));
}

/**
 * UPDATE: Deactivate a checklist
 */
export async function deactivateChecklist(checklistId: string) {
	const result = await db
		.update(resumeChecklist)
		.set({
			isActive: false,
			updatedAt: new Date(),
		})
		.where(eq(resumeChecklist.id, checklistId))
		.returning();

	return result[0];
}

/**
 * CREATE: Create an evaluation
 */
export async function createEvaluation({
	resumeId,
	studentId,
	tenantId,
	checklistId,
	evaluatedBy,
	isAutoGenerated = false,
	items,
}: {
	resumeId: string;
	studentId: string;
	tenantId: string;
	checklistId: string;
	evaluatedBy: string;
	isAutoGenerated?: boolean;
	items: Array<{
		checklistItemId: string;
		passed: boolean;
		notes?: string;
		score?: number;
	}>;
}) {
	const evaluationId = crypto.randomUUID();

	// Calculate overall score (average of item scores or weights)
	const totalScore = items.reduce((sum, item) => sum + (item.score ?? 0), 0);
	const overallScore = items.length > 0 ? totalScore / items.length : null;

	// Create evaluation
	const evalResult = await db
		.insert(resumeEvaluation)
		.values({
			id: evaluationId,
			resumeId,
			studentId,
			tenantId,
			checklistId,
			overallScore,
			isAutoGenerated,
			evaluatedBy,
			evaluatedAt: new Date(),
			createdAt: new Date(),
			updatedAt: new Date(),
		})
		.returning();

	// Create evaluation items
	const itemsResult = await db
		.insert(resumeEvaluationItem)
		.values(
			items.map((item) => ({
				id: crypto.randomUUID(),
				evaluationId,
				checklistItemId: item.checklistItemId,
				passed: item.passed,
				notes: item.notes,
				score: item.score,
				createdAt: new Date(),
			}))
		)
		.returning();

	return {
		...evalResult[0],
		items: itemsResult,
	};
}

/**
 * READ: Get evaluation by ID with items
 */
export async function getEvaluationById(evaluationId: string) {
	const evaluation = await db
		.select()
		.from(resumeEvaluation)
		.where(eq(resumeEvaluation.id, evaluationId));

	if (!evaluation.length) return null;

	const items = await db
		.select()
		.from(resumeEvaluationItem)
		.where(eq(resumeEvaluationItem.evaluationId, evaluationId));

	return {
		...evaluation[0],
		items,
	};
}

/**
 * READ: List evaluations for a resume
 */
export async function getEvaluationsByResumeId(resumeId: string) {
	const evaluations = await db
		.select()
		.from(resumeEvaluation)
		.where(eq(resumeEvaluation.resumeId, resumeId))
		.orderBy(desc(resumeEvaluation.evaluatedAt));

	// Fetch items for each evaluation
	const evaluationsWithItems = await Promise.all(
		evaluations.map(async (evaluation) => {
			const items = await db
				.select()
				.from(resumeEvaluationItem)
				.where(eq(resumeEvaluationItem.evaluationId, evaluation.id));

			return {
				...evaluation,
				items,
			};
		})
	);

	return evaluationsWithItems;
}

/**
 * CREATE: Add to resume history audit trail
 */
export async function addToHistory({
	resumeId,
	studentId,
	tenantId,
	action,
	changedBy,
	actorType,
	previousData,
	currentData,
}: {
	resumeId: string;
	studentId: string;
	tenantId: string;
	action: "CREATED" | "UPDATED" | "COMMENTED" | "EVALUATED" | "FORWARDED";
	changedBy: string;
	actorType: "STUDENT" | "FACULTY" | "PO" | "ADMIN";
	previousData?: unknown;
	currentData?: unknown;
}) {
	const result = await db
		.insert(resumeHistory)
		.values({
			id: crypto.randomUUID(),
			resumeId,
			studentId,
			tenantId,
			action,
			changedBy,
			actorType,
			previousData: previousData ? JSON.stringify(previousData) : null,
			currentData: currentData ? JSON.stringify(currentData) : null,
			createdAt: new Date(),
		})
		.returning();

	return result[0];
}

/**
 * READ: Get resume history timeline
 */
export async function getResumeHistory(resumeId: string) {
	const history = await db
		.select()
		.from(resumeHistory)
		.where(eq(resumeHistory.resumeId, resumeId))
		.orderBy(desc(resumeHistory.createdAt));

	return history;
}

/**
 * READ: Get history for a student across all resumes
 */
export async function getStudentHistory(studentId: string, tenantId: string) {
	const history = await db
		.select()
		.from(resumeHistory)
		.where(and(eq(resumeHistory.studentId, studentId), eq(resumeHistory.tenantId, tenantId)))
		.orderBy(desc(resumeHistory.createdAt));

	return history;
}
