import { scryptSync } from "node:crypto";
import { createFileRoute } from "@tanstack/react-router";
// @ts-expect-error
import jwt from "jsonwebtoken";
import { auth, DEFAULT_RESUME_USER_ORG_ID, DEFAULT_RESUME_USER_TENANT_ID } from "@/integrations/auth/config";
import { dlog } from "@/utils/debug";
import { env } from "@/utils/env";

function tenantOrgFromJwt(decoded: Record<string, unknown>): { tenantId: string; organisationId: string } {
	const tenantRaw = decoded.tenantId ?? decoded.tenant_id;
	const orgRaw = decoded.organisationId ?? decoded.organisation_id ?? decoded.org_id;
	const tenantId = typeof tenantRaw === "string" && tenantRaw.length > 0 ? tenantRaw : DEFAULT_RESUME_USER_TENANT_ID;
	const organisationId = typeof orgRaw === "string" && orgRaw.length > 0 ? orgRaw : DEFAULT_RESUME_USER_ORG_ID;
	return { tenantId, organisationId };
}

/** Prefer eng-labs PK (`user_id`, …); `userId` is often Firebase/auth and won't match `users.id`. */
function engLabsUserIdFromJwt(decoded: Record<string, unknown>): string | null {
	const candidates = [decoded.eng_labs_user_id, decoded.user_id, decoded.engLabsUserId, decoded.userId];
	for (const c of candidates) {
		if (typeof c === "string" && c.length > 0) return c;
	}
	return null;
}

async function handler({ request }: { request: Request }) {
	const url = new URL(request.url);
	const token = url.searchParams.get("token");
	const traceId = url.searchParams.get("trace") ?? `sso-${Date.now().toString(36)}`;

	dlog("sso", "request:received", {
		traceId,
		host: url.host,
		path: url.pathname,
		hasToken: !!token,
		referrer: request.headers.get("referer") ?? null,
		ua: request.headers.get("user-agent")?.slice(0, 100) ?? null,
	});

	const errorRedirect = (error: string) => {
		dlog("sso", "request:error-redirect", { traceId, error });
		return new Response(null, {
			status: 302,
			headers: {
				Location: `/resume/auth/login?error=${error}&trace=${encodeURIComponent(traceId)}`,
			},
		});
	};

	if (!token) {
		return errorRedirect("missing_token");
	}

	try {
		// Prioritize MAIN_APP_SECRET for SSO verification as the token is generated by the parent app
		const secret = env.MAIN_APP_SECRET || env.AUTH_SECRET;

		if (!secret) {
			console.error("Missing MAIN_APP_SECRET or AUTH_SECRET");
			return errorRedirect("server_configuration");
		}

		const decoded = jwt.verify(token, secret) as Record<string, unknown> & {
			email: string;
			name: string;
			username: string;
			userId: string;
			source_url?: string;
			role?: string;
			tenantId?: string;
			organisationId?: string;
			tenant_id?: string;
			organisation_id?: string;
			organisationUnits?: string[];
		};

		console.log(
			"[SSO] Decoded JWT payload:",
			JSON.stringify(
				{
					email: decoded.email,
					name: decoded.name,
					username: decoded.username,
					userId: decoded.userId,
					role: decoded.role ?? "NOT_SET",
					tenantId: decoded.tenantId ?? "NOT_SET",
					organisationId: decoded.organisationId ?? "NOT_SET",
					organisationUnits: decoded.organisationUnits ?? "NOT_SET",
					source_url: decoded.source_url ?? "NOT_SET",
				},
				null,
				2,
			),
		);

		if (!decoded.email) {
			return errorRedirect("invalid_token_payload");
		}

		const { tenantId: resolvedTenantId, organisationId: resolvedOrganisationId } = tenantOrgFromJwt(decoded);

		// Generate deterministic password (32 bytes -> 64 hex chars, fitting maxPasswordLength: 64)
		const password = scryptSync(decoded.email, secret, 32).toString("hex");

		// Try to sign in
		let response = await auth.api.signInEmail({
			body: {
				email: decoded.email,
				password,
			},
			asResponse: true,
		});
		dlog("sso", "signin:attempt", { traceId, ok: response.ok, status: response.status });

		// If sign in fails, try to sign up
		if (!response.ok) {
			response = await auth.api.signUpEmail({
				body: {
					email: decoded.email,
					password,
					name: decoded.name,
					username: decoded.username || decoded.email.split("@")[0],
					tenantId: resolvedTenantId,
					organisationId: resolvedOrganisationId,
				},
				asResponse: true,
			});
			dlog("sso", "signup:attempt", { traceId, ok: response.ok, status: response.status });
		}

		if (!response.ok) {
			console.error("Failed to sign in/up user via SSO", await response.text());
			return errorRedirect("sso_failed");
		}

		// Redirect to an intermediate HTML page that stores SSO context in localStorage
		// then redirects to /dashboard. We can't use Set-Cookie (runtime merges headers)
		// or query params (TanStack Router strips unknown search params).
		const ssoContext = {
			source_url: decoded.source_url ?? null,
			// Normalize role to uppercase so sidebar comparisons are case-insensitive
			role: (() => {
				if (!decoded.role) return null;
				const r = decoded.role.toUpperCase().replace(/[- ]/g, "_");
				if (r === "PO" || r === "PLACEMENT_OFFICER" || r === "PLACEMENT_ADMIN") return "PLACEMENT_OFFICER";
				if (r === "FACULTY" || r === "INSTRUCTOR") return "INSTRUCTOR";
				if (r === "STUDENT" || r === "LEARNER") return "LEARNER";
				return r;
			})(),
			engLabsUserId: engLabsUserIdFromJwt(decoded),
			tenantId: resolvedTenantId,
			organisationId: resolvedOrganisationId,
			organisationUnits: decoded.organisationUnits ?? [],
			trace: traceId,
		};

		console.log("[SSO] Passing sso_context via intermediate page:", JSON.stringify(ssoContext));

		const roleUpper = ssoContext.role?.toUpperCase();
		const destination =
			roleUpper === "INSTRUCTOR"
				? "/resume/dashboard/faculty?tab=overview"
				: roleUpper === "PLACEMENT_OFFICER"
					? "/resume/dashboard/placement-officer?tab=overview"
					: roleUpper === "ADMIN"
						? "/resume/dashboard/admin?tab=overview"
						: "/resume/dashboard/resumes?sort=lastUpdatedAt";

		const setCookieCount = Array.from(response.headers.entries()).filter(
			([k]) => k.toLowerCase() === "set-cookie",
		).length;
		dlog("sso", "destination:resolved", {
			traceId,
			roleUpper,
			destination,
			setCookieCount,
			ssoContext: { ...ssoContext, organisationUnits: ssoContext.organisationUnits.length },
		});

		const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head><body>
<script>
localStorage.setItem("sso_context", ${JSON.stringify(JSON.stringify(ssoContext))});
window.location.replace(${JSON.stringify(destination)});
</script>
<noscript><a href="${destination}">Continue to dashboard</a></noscript>
</body></html>`;

		// Forward auth cookies from better-auth on the HTML response
		const responseHeaders = new Headers({ "Content-Type": "text/html; charset=utf-8" });
		response.headers.forEach((value, key) => {
			if (key.toLowerCase() === "set-cookie") {
				responseHeaders.append(key, value);
			}
		});

		// So SSR matches the client: localStorage holds `source_url` in sso_context, but the server
		// cannot read it — mirror into a cookie for getSourceUrl() / exit links (hydration-safe hrefs).
		if (decoded.source_url) {
			const enc = encodeURIComponent(decoded.source_url);
			const secure = url.protocol === "https:" ? "; Secure" : "";
			responseHeaders.append(
				"Set-Cookie",
				`source_url=${enc}; Path=/resume; Max-Age=${60 * 60 * 24 * 180}; SameSite=Lax${secure}`,
			);
		}

		return new Response(html, { status: 200, headers: responseHeaders });
	} catch (e) {
		console.error(`[SSOTrace:${traceId}] token:verify_failed`, e);
		return errorRedirect("invalid_token");
	}
}

export const Route = createFileRoute("/api/auth/sso")({
	server: {
		handlers: {
			GET: handler,
		},
	},
});
