import { scryptSync } from "node:crypto";
import { createFileRoute } from "@tanstack/react-router";
import { setResponseHeader } from "@tanstack/react-start/server";
// @ts-expect-error
import jwt from "jsonwebtoken";
import { auth, DEFAULT_RESUME_USER_ORG_ID, DEFAULT_RESUME_USER_TENANT_ID } from "@/integrations/auth/config";
import { dlog } from "@/utils/debug";
import { env } from "@/utils/env";

function tenantOrgFromJwt(decoded: Record<string, unknown>): { tenantId: string; organisationId: string } {
	const tenantRaw = decoded.tenantId ?? decoded.tenant_id;
	const orgRaw = decoded.organisationId ?? decoded.organisation_id ?? decoded.org_id;
	const tenantId = typeof tenantRaw === "string" && tenantRaw.length > 0 ? tenantRaw : DEFAULT_RESUME_USER_TENANT_ID;
	const organisationId = typeof orgRaw === "string" && orgRaw.length > 0 ? orgRaw : DEFAULT_RESUME_USER_ORG_ID;
	return { tenantId, organisationId };
}

/** Prefer eng-labs PK (`user_id`, …); `userId` is often Firebase/auth and won't match `users.id`. */
function engLabsUserIdFromJwt(decoded: Record<string, unknown>): string | null {
	const candidates = [decoded.eng_labs_user_id, decoded.user_id, decoded.engLabsUserId, decoded.userId];
	for (const c of candidates) {
		if (typeof c === "string" && c.length > 0) return c;
	}
	return null;
}

async function handler({ request }: { request: Request }) {
	const url = new URL(request.url);
	const token = url.searchParams.get("token");
	const traceId = url.searchParams.get("trace") ?? `sso-${Date.now().toString(36)}`;

	dlog("sso", "request:received", {
		traceId,
		host: url.host,
		path: url.pathname,
		hasToken: !!token,
		referrer: request.headers.get("referer") ?? null,
		ua: request.headers.get("user-agent")?.slice(0, 100) ?? null,
	});

	const errorRedirect = (error: string) => {
		dlog("sso", "request:error-redirect", { traceId, error });
		return new Response(null, {
			status: 302,
			headers: {
				Location: `/resume/auth/login?error=${error}&trace=${encodeURIComponent(traceId)}`,
			},
		});
	};

	if (!token) {
		return errorRedirect("missing_token");
	}

	try {
		// Prioritize MAIN_APP_SECRET for SSO verification as the token is generated by the parent app
		const secret = env.MAIN_APP_SECRET || env.AUTH_SECRET;

		if (!secret) {
			console.error("Missing MAIN_APP_SECRET or AUTH_SECRET");
			return errorRedirect("server_configuration");
		}

		const decoded = jwt.verify(token, secret) as Record<string, unknown> & {
			email: string;
			name: string;
			username: string;
			userId: string;
			source_url?: string;
			role?: string;
			tenantId?: string;
			organisationId?: string;
			tenant_id?: string;
			organisation_id?: string;
			organisationUnits?: string[];
		};

		console.log(
			"[SSO] Decoded JWT payload:",
			JSON.stringify(
				{
					email: decoded.email,
					name: decoded.name,
					username: decoded.username,
					userId: decoded.userId,
					role: decoded.role ?? "NOT_SET",
					tenantId: decoded.tenantId ?? "NOT_SET",
					organisationId: decoded.organisationId ?? "NOT_SET",
					organisationUnits: decoded.organisationUnits ?? "NOT_SET",
					source_url: decoded.source_url ?? "NOT_SET",
				},
				null,
				2,
			),
		);

		if (!decoded.email) {
			return errorRedirect("invalid_token_payload");
		}

		const { tenantId: resolvedTenantId, organisationId: resolvedOrganisationId } = tenantOrgFromJwt(decoded);

		// Generate deterministic password (32 bytes -> 64 hex chars, fitting maxPasswordLength: 64)
		const password = scryptSync(decoded.email, secret, 32).toString("hex");

		// Try to sign in
		let response = await auth.api.signInEmail({
			body: {
				email: decoded.email,
				password,
			},
			asResponse: true,
		});
		dlog("sso", "signin:attempt", { traceId, ok: response.ok, status: response.status });

		// If sign in fails, try to sign up
		if (!response.ok) {
			response = await auth.api.signUpEmail({
				body: {
					email: decoded.email,
					password,
					name: decoded.name,
					username: decoded.username || decoded.email.split("@")[0],
					tenantId: resolvedTenantId,
					organisationId: resolvedOrganisationId,
				},
				asResponse: true,
			});
			dlog("sso", "signup:attempt", { traceId, ok: response.ok, status: response.status });
		}

		if (!response.ok) {
			console.error("Failed to sign in/up user via SSO", await response.text());
			return errorRedirect("sso_failed");
		}

		// Redirect to an intermediate HTML page that stores SSO context in localStorage
		// then redirects to /dashboard. We can't use Set-Cookie (runtime merges headers)
		// or query params (TanStack Router strips unknown search params).
		const ssoContext = {
			source_url: decoded.source_url ?? null,
			// Normalize role to uppercase so sidebar comparisons are case-insensitive
			role: (() => {
				if (!decoded.role) return null;
				const r = decoded.role.toUpperCase().replace(/[- ]/g, "_");
				if (r === "PO" || r === "PLACEMENT_OFFICER" || r === "PLACEMENT_ADMIN") return "PLACEMENT_OFFICER";
				if (r === "FACULTY" || r === "INSTRUCTOR") return "INSTRUCTOR";
				if (r === "STUDENT" || r === "LEARNER") return "LEARNER";
				return r;
			})(),
			engLabsUserId: engLabsUserIdFromJwt(decoded),
			tenantId: resolvedTenantId,
			organisationId: resolvedOrganisationId,
			organisationUnits: decoded.organisationUnits ?? [],
			trace: traceId,
		};

		console.log("[SSO] Passing sso_context via intermediate page:", JSON.stringify(ssoContext));

		const roleUpper = ssoContext.role?.toUpperCase();
		const destination =
			roleUpper === "INSTRUCTOR"
				? "/resume/dashboard/faculty?tab=overview"
				: roleUpper === "PLACEMENT_OFFICER"
					? "/resume/dashboard/placement-officer?tab=overview"
					: roleUpper === "ADMIN"
						? "/resume/dashboard/admin?tab=overview"
						: "/resume/dashboard/resumes?sort=lastUpdatedAt";

		const setCookieCount = Array.from(response.headers.entries()).filter(
			([k]) => k.toLowerCase() === "set-cookie",
		).length;
		dlog("sso", "destination:resolved", {
			traceId,
			roleUpper,
			destination,
			setCookieCount,
			ssoContext: { ...ssoContext, organisationUnits: ssoContext.organisationUnits.length },
		});

		// IMPORTANT: respond with a real 302 redirect, not an HTML page that scripts-then-navigates.
		//
		// The previous version returned HTML containing `localStorage.setItem(...)` +
		// `window.location.replace(destination)`. Browsers usually commit Set-Cookie before running
		// inline scripts, but in practice there's a race (Chrome under load, cold container, etc.)
		// where the navigation fires before the cookie is fully attached to outgoing requests. That
		// race is the entire reason first-SSO users saw a 307 from /dashboard/admin to /auth/login:
		// the very next request after this response went out without the auth cookie that we'd just
		// issued, so the server's getSession() returned null and the dashboard's beforeLoad
		// redirected them to /auth/login.
		//
		// HTTP spec is unambiguous about redirects: the browser MUST commit Set-Cookie headers
		// before following Location. Switching to a 302 closes the race entirely — the cookie is
		// guaranteed to ride on the next request.
		//
		// `sso_context` previously lived in localStorage (set by the inline script). We now write it
		// as a cookie instead so the server can deliver it atomically with the auth cookie.
		// sso-context.ts reads from `document.cookie` first, with localStorage as a fallback for
		// users whose entry was set by the previous HTML+script version of this handler.

		const isSecure = url.protocol === "https:";
		const secureAttr = isSecure ? "; Secure" : "";

		// Vite dev pipeline (start-plugin-core + srvx) drops all but the LAST set-cookie in the
		// response. Production (Hono node-server) doesn't have this bug. Until the framework
		// is patched, we put Better Auth's session cookie LAST so it's the one that survives —
		// it's the only cookie that's strictly required (without it `auth.api.getSession()`
		// returns null and the dashboard bounces). The other two (`sso_context`, `source_url`)
		// are written but will be dropped in dev; they survive in prod. The client recovers
		// `sso_context` data from the Better Auth user record via ORPC — see TODO below.
		const setCookies: string[] = [];
		setCookies.push(
			`sso_context=${encodeURIComponent(JSON.stringify(ssoContext))}; Path=/resume; Max-Age=${60 * 60 * 24 * 30}; SameSite=Lax${secureAttr}`,
		);
		if (decoded.source_url) {
			setCookies.push(
				`source_url=${encodeURIComponent(decoded.source_url)}; Path=/resume; Max-Age=${60 * 60 * 24 * 180}; SameSite=Lax${secureAttr}`,
			);
		}
		setCookies.push(...response.headers.getSetCookie());
		setResponseHeader("set-cookie", setCookies);

		// `sso_context` ALSO travels via the redirect URL's hash fragment as a backup channel.
		// In `pnpm dev` the Vite response pipeline drops all-but-one Set-Cookie, so the cookie
		// version of `sso_context` won't reach the browser — but the hash fragment rides on the
		// navigation regardless. Client-side `getSsoContext` (sso-context.ts) reads from the hash
		// on first dashboard render and persists to localStorage. In prod the cookie wins; the
		// hash is then quietly stripped out. Same code path, both environments work.
		const ssoContextHash = encodeURIComponent(JSON.stringify(ssoContext));
		const destinationWithHash = `${destination}#sso=${ssoContextHash}`;

		console.log("[SSO] setCookies handed to framework:", setCookies.length, setCookies.map((c) => c.split("=")[0]));

		return new Response(null, {
			status: 302,
			headers: {
				Location: destinationWithHash,
				"Cache-Control": "no-store",
			},
		});
	} catch (e) {
		console.error(`[SSOTrace:${traceId}] token:verify_failed`, e);
		return errorRedirect("invalid_token");
	}
}

export const Route = createFileRoute("/api/auth/sso")({
	server: {
		handlers: {
			GET: handler,
		},
	},
});
