import { scryptSync } from "node:crypto";
import { createFileRoute } from "@tanstack/react-router";
// @ts-expect-error
import jwt from "jsonwebtoken";
import { auth } from "@/integrations/auth/config";
import { env } from "@/utils/env";

async function handler({ request }: { request: Request }) {
	const url = new URL(request.url);
	const token = url.searchParams.get("token");
	const traceId = url.searchParams.get("trace") ?? `sso-${Date.now().toString(36)}`;

	const errorRedirect = (error: string) => {
		return new Response(null, {
			status: 302,
			headers: {
				Location: `/resume/auth/login?error=${error}&trace=${encodeURIComponent(traceId)}`,
			},
		});
	};

	if (!token) {
		return errorRedirect("missing_token");
	}

	try {
		// Prioritize MAIN_APP_SECRET for SSO verification as the token is generated by the parent app
		const secret = env.MAIN_APP_SECRET || env.AUTH_SECRET;

		if (!secret) {
			console.error("Missing MAIN_APP_SECRET or AUTH_SECRET");
			return errorRedirect("server_configuration");
		}

		const decoded = jwt.verify(token, secret) as {
			email: string;
			name: string;
			username: string;
			userId: string;
			source_url?: string;
			role?: string;
			tenantId?: string;
			organisationId?: string;
			organisationUnits?: string[];
		};

		console.log(
			"[SSO] Decoded JWT payload:",
			JSON.stringify(
				{
					email: decoded.email,
					name: decoded.name,
					username: decoded.username,
					userId: decoded.userId,
					role: decoded.role ?? "NOT_SET",
					tenantId: decoded.tenantId ?? "NOT_SET",
					organisationId: decoded.organisationId ?? "NOT_SET",
					organisationUnits: decoded.organisationUnits ?? "NOT_SET",
					source_url: decoded.source_url ?? "NOT_SET",
				},
				null,
				2,
			),
		);

		if (!decoded.email) {
			return errorRedirect("invalid_token_payload");
		}

		// Generate deterministic password (32 bytes -> 64 hex chars, fitting maxPasswordLength: 64)
		const password = scryptSync(decoded.email, secret, 32).toString("hex");

		// Try to sign in
		let response = await auth.api.signInEmail({
			body: {
				email: decoded.email,
				password,
			},
			asResponse: true,
		});

		// If sign in fails, try to sign up
		if (!response.ok) {
			response = await auth.api.signUpEmail({
				body: {
					email: decoded.email,
					password,
					name: decoded.name,
					username: decoded.username || decoded.email.split("@")[0],
				},
				asResponse: true,
			});
		}

		if (!response.ok) {
			console.error("Failed to sign in/up user via SSO", await response.text());
			return errorRedirect("sso_failed");
		}

		// Redirect to an intermediate HTML page that stores SSO context in localStorage
		// then redirects to /dashboard. We can't use Set-Cookie (runtime merges headers)
		// or query params (TanStack Router strips unknown search params).
		const ssoContext = {
			source_url: decoded.source_url ?? null,
			// Normalize role to uppercase so sidebar comparisons are case-insensitive
			role: (() => {
				if (!decoded.role) return null;
				const r = decoded.role.toUpperCase().replace(/[- ]/g, "_");
				if (r === "PO" || r === "PLACEMENT_OFFICER" || r === "PLACEMENT_ADMIN") return "PLACEMENT_OFFICER";
				if (r === "FACULTY" || r === "INSTRUCTOR") return "INSTRUCTOR";
				if (r === "STUDENT" || r === "LEARNER") return "LEARNER";
				return r;
			})(),
			engLabsUserId: decoded.userId ?? null,
			tenantId: decoded.tenantId ?? null,
			organisationId: decoded.organisationId ?? null,
			organisationUnits: decoded.organisationUnits ?? [],
			trace: traceId,
		};

		console.log("[SSO] Passing sso_context via intermediate page:", JSON.stringify(ssoContext));

		const roleUpper = ssoContext.role?.toUpperCase();
		const destination =
			roleUpper === "INSTRUCTOR"
				? "/resume/dashboard/faculty?tab=overview"
				: roleUpper === "PLACEMENT_OFFICER"
					? "/resume/dashboard/placement-officer?tab=overview"
					: roleUpper === "ADMIN"
						? "/resume/dashboard/admin"
						: "/resume/dashboard/resumes?sort=lastUpdatedAt";

		const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head><body>
<script>
localStorage.setItem("sso_context", ${JSON.stringify(JSON.stringify(ssoContext))});
window.location.replace(${JSON.stringify(destination)});
</script>
<noscript><a href="${destination}">Continue to dashboard</a></noscript>
</body></html>`;

		// Forward auth cookies from better-auth on the HTML response
		const responseHeaders = new Headers({ "Content-Type": "text/html; charset=utf-8" });
		response.headers.forEach((value, key) => {
			if (key.toLowerCase() === "set-cookie") {
				responseHeaders.append(key, value);
			}
		});

		return new Response(html, { status: 200, headers: responseHeaders });
	} catch (e) {
		console.error(`[SSOTrace:${traceId}] token:verify_failed`, e);
		return errorRedirect("invalid_token");
	}
}

export const Route = createFileRoute("/api/auth/sso")({
	server: {
		handlers: {
			GET: handler,
		},
	},
});
